[profile.release]
debug = true

[workspace]
members = ["crates/*"]

[patch.crates-io]
# https://github.com/SoftbearStudios/bitcode/issues/2
bitcode = { git = "https://github.com/softbearstudios/bitcode" }
