//! Tests that the padding and validation code generated by the `ZeroCopy`
//! derive agrees with the layout the compiler picks for a type.

use core::mem::{offset_of, size_of};

use alloc::string::ToString;

use anyhow::Result;

use crate::{OwnedBuf, Ref, ZeroCopy};

/// Load a `T` from `bytes` placed at offset 0 of a buffer aligned for `T`.
fn load_bytes<T>(bytes: &[u8]) -> Result<T, crate::Error>
where
    T: ZeroCopy + Copy,
{
    let mut buf = OwnedBuf::with_alignment::<T>();
    buf.extend_from_slice(bytes).unwrap();
    buf.load(Ref::<T>::new(0u32)).copied()
}

/// In `repr(packed(N))` each field is aligned to `min(N, align_of::<F>())`, so
/// fields with a smaller alignment than `N` keep their natural alignment.
#[derive(Clone, Copy, ZeroCopy)]
#[repr(C, packed(4))]
#[zero_copy(crate)]
struct PackedBool {
    a: u8,
    b: bool,
    c: u16,
    d: u8,
}

#[test]
fn packed_n_layout() {
    assert_eq!(offset_of!(PackedBool, a), 0);
    assert_eq!(offset_of!(PackedBool, b), 1);
    assert_eq!(offset_of!(PackedBool, c), 2);
    assert_eq!(offset_of!(PackedBool, d), 4);
    assert_eq!(size_of::<PackedBool>(), 6);

    assert_eq!(offset_of!(PackedPad, a), 0);
    assert_eq!(offset_of!(PackedPad, b), 1);
    assert_eq!(offset_of!(PackedPad, c), 4);
    assert_eq!(size_of::<PackedPad>(), 8);
}

#[test]
fn packed_n_validate_rejects_invalid_field() {
    // `b` holds 2, which is not a valid bool.
    let Err(error) = load_bytes::<PackedBool>(&[0, 2, 0, 0, 0, 0]) else {
        panic!("expected an invalid bool error");
    };
    assert_eq!(error.to_string(), "Invalid bool representation 2");
}

#[test]
fn packed_n_validate_accepts_valid_field() {
    // `b` is valid, `d` is an arbitrary byte which must not be validated as a
    // bool.
    let value = load_bytes::<PackedBool>(&[7, 1, 0x34, 0x12, 2, 0]).unwrap();
    let (a, b, d) = (value.a, value.b, value.d);
    assert_eq!((a, b, d), (7, true, 2));
}

#[derive(Clone, Copy, ZeroCopy)]
#[repr(C, packed(4))]
#[zero_copy(crate)]
struct PackedPad {
    a: u8,
    b: u8,
    c: u32,
}

#[test]
fn packed_n_pad_preserves_fields() -> Result<()> {
    const _: () = assert!(PackedPad::PADDED);

    let mut buf = OwnedBuf::new();
    buf.store(&PackedPad {
        a: 1,
        b: 2,
        c: u32::from_ne_bytes([3, 4, 5, 6]),
    })?;

    assert_eq!(buf.as_slice(), &[1, 2, 0, 0, 3, 4, 5, 6]);
    Ok(())
}
